"""create sources and query_bank tables

Revision ID: 221bb5995531
Revises: 0a1e68db884a
Create Date: 2026-04-14 13:09:49.881268

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '221bb5995531'
down_revision: str | None = '0a1e68db884a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('segment_tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('new_properties', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("property_type IN ('boutique_hotel', 'villa', 'bungalow', 'heritage_home', 'farmhouse', 'resort', 'banquet_hall', 'cafe', 'restaurant', 'warehouse', 'industrial_shed', 'office_space', 'school_campus', 'coworking_space', 'rooftop_venue', 'theatre_studio', 'club_lounge', 'other')", name='ck_query_bank_property_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text', 'city', name='uq_query_bank_text_city')
    )
    op.create_index('idx_query_bank_city_enabled', 'query_bank', ['city'], unique=False, postgresql_where='is_enabled = true')
    op.create_index('idx_query_bank_quality', 'query_bank', ['quality_score'], unique=False, postgresql_ops={'quality_score': 'DESC NULLS LAST'})
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('access_policy', sa.String(length=20), nullable=False),
    sa.Column('crawl_method', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('refresh_frequency', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_policy IN ('allowed', 'manual_only', 'restricted')", name='ck_sources_access_policy'),
    sa.CheckConstraint("crawl_method IN ('api_call', 'sitemap', 'html_parser', 'browser_render')", name='ck_sources_crawl_method'),
    sa.CheckConstraint("refresh_frequency IN ('hourly', 'daily', 'weekly', 'monthly')", name='ck_sources_refresh_frequency'),
    sa.CheckConstraint("source_type IN ('api', 'website', 'manual', 'partner_feed')", name='ck_sources_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_index('idx_sources_enabled_type', 'sources', ['source_type'], unique=False, postgresql_where='is_enabled = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sources_enabled_type', table_name='sources', postgresql_where='is_enabled = true')
    op.drop_table('sources')
    op.drop_index('idx_query_bank_quality', table_name='query_bank', postgresql_ops={'quality_score': 'DESC NULLS LAST'})
    op.drop_index('idx_query_bank_city_enabled', table_name='query_bank', postgresql_where='is_enabled = true')
    op.drop_table('query_bank')
    # ### end Alembic commands ###
