"""add properties, property_contacts and do_not_contact tables

Revision ID: 28197a269f8b
Revises: 4af2187029ca
Create Date: 2026-04-14 15:46:06.221044

"""
from collections.abc import Sequence

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28197a269f8b'
down_revision: str | None = '4af2187029ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('do_not_contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contact_type IN ('phone', 'email', 'whatsapp', 'domain')", name='ck_do_not_contact_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_type', 'contact_value', name='uq_do_not_contact_type_value')
    )
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_address', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography').with_variant(sa.String(length=255), 'sqlite'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('canonical_website', sa.String(length=500), nullable=True),
    sa.Column('canonical_phone', sa.String(length=50), nullable=True),
    sa.Column('canonical_email', sa.String(length=255), nullable=True),
    sa.Column('short_brief', sa.Text(), nullable=True),
    sa.Column('brief_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('score_reason_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('google_place_id', sa.String(length=300), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("property_type IN ('boutique_hotel', 'villa', 'bungalow', 'heritage_home', 'farmhouse', 'resort', 'banquet_hall', 'cafe', 'restaurant', 'warehouse', 'industrial_shed', 'office_space', 'school_campus', 'coworking_space', 'rooftop_venue', 'theatre_studio', 'club_lounge', 'other')", name='ck_properties_property_type'),
    sa.CheckConstraint("status IN ('new', 'reviewed', 'approved', 'rejected', 'onboarded', 'do_not_contact')", name='ck_properties_status'),
    sa.CheckConstraint('relevance_score IS NULL OR (relevance_score >= 0 AND relevance_score <= 1)', name='ck_properties_score_range'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_properties_dashboard', 'properties', ['city', 'property_type', 'status', 'relevance_score'], unique=False, postgresql_ops={'relevance_score': 'DESC NULLS LAST'})
    # idx_properties_location (GIST on Geography column) is auto-created by GeoAlchemy2.
    op.create_index('idx_properties_unbriefed', 'properties', ['scored_at'], unique=False, postgresql_where='brief_generated_at IS NULL AND scored_at IS NOT NULL')
    op.create_index('idx_properties_unscored', 'properties', ['created_at'], unique=False, postgresql_where='scored_at IS NULL')
    op.create_table('property_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_public_business_contact', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('flagged_personal', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contact_type IN ('phone', 'email', 'whatsapp', 'form', 'website', 'instagram')", name='ck_property_contacts_type'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_property_contacts_confidence_range'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'contact_type', 'normalized_value', name='uq_property_contacts_property_type_value')
    )
    op.create_index('idx_contacts_email_dedup', 'property_contacts', ['normalized_value'], unique=False, postgresql_where="contact_type = 'email'")
    op.create_index('idx_contacts_flagged', 'property_contacts', ['flagged_personal'], unique=False, postgresql_where='flagged_personal = true')
    op.create_index('idx_contacts_phone_dedup', 'property_contacts', ['normalized_value'], unique=False, postgresql_where="contact_type = 'phone'")
    op.create_index('idx_contacts_property', 'property_contacts', ['property_id'], unique=False)
    op.drop_index(op.f('idx_query_bank_quality'), table_name='query_bank')
    op.create_index('idx_query_bank_quality', 'query_bank', ['quality_score'], unique=False, postgresql_ops={'quality_score': 'DESC NULLS LAST'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_query_bank_quality', table_name='query_bank', postgresql_ops={'quality_score': 'DESC NULLS LAST'})
    op.create_index(op.f('idx_query_bank_quality'), 'query_bank', [sa.literal_column('quality_score DESC NULLS LAST')], unique=False)
    op.drop_index('idx_contacts_property', table_name='property_contacts')
    op.drop_index('idx_contacts_phone_dedup', table_name='property_contacts', postgresql_where="contact_type = 'phone'")
    op.drop_index('idx_contacts_flagged', table_name='property_contacts', postgresql_where='flagged_personal = true')
    op.drop_index('idx_contacts_email_dedup', table_name='property_contacts', postgresql_where="contact_type = 'email'")
    op.drop_table('property_contacts')
    op.drop_index('idx_properties_unscored', table_name='properties', postgresql_where='scored_at IS NULL')
    op.drop_index('idx_properties_unbriefed', table_name='properties', postgresql_where='brief_generated_at IS NULL AND scored_at IS NOT NULL')
    # idx_properties_location is dropped automatically when the table is dropped.
    op.drop_index('idx_properties_dashboard', table_name='properties', postgresql_ops={'relevance_score': 'DESC NULLS LAST'})
    op.drop_table('properties')
    op.drop_table('do_not_contact')
    # ### end Alembic commands ###
