"""add users and outreach_queue tables

Revision ID: 4875a0dc2f58
Revises: eeff978b8742
Create Date: 2026-04-15 11:42:39.715721

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4875a0dc2f58'
down_revision: str | None = 'eeff978b8742'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'reviewer', 'sales', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(
        'idx_users_email_lower',
        'users',
        [sa.text('lower(email)')],
        unique=True,
    )
    op.create_table('outreach_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('outreach_channel', sa.String(length=20), nullable=True),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_attempts', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outreach_channel IS NULL OR outreach_channel IN ('phone', 'email', 'whatsapp', 'form', 'in_person')", name='ck_outreach_channel'),
    sa.CheckConstraint("status IN ('pending', 'contacted', 'responded', 'follow_up', 'converted', 'declined', 'no_response')", name='ck_outreach_status'),
    sa.CheckConstraint('priority >= 1 AND priority <= 100', name='ck_outreach_priority_range'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', name='uq_outreach_property')
    )
    op.create_index('idx_outreach_assigned_status', 'outreach_queue', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_outreach_follow_up', 'outreach_queue', ['follow_up_at'], unique=False, postgresql_where="follow_up_at IS NOT NULL AND status IN ('contacted', 'follow_up')")
    op.create_index('idx_outreach_priority', 'outreach_queue', ['priority', 'created_at'], unique=False, postgresql_where="status = 'pending'", postgresql_ops={'priority': 'DESC'})
    # NOTE: skipped cosmetic drop+recreate of idx_properties_dashboard,
    # idx_query_bank_quality, idx_properties_location, idx_properties_normalized_name_trgm
    # — autogenerate detects them as changed due to DESC NULLS LAST and raw-SQL
    # expression differences but they are functionally correct on disk.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('idx_outreach_priority', table_name='outreach_queue', postgresql_where="status = 'pending'", postgresql_ops={'priority': 'DESC'})
    op.drop_index('idx_outreach_follow_up', table_name='outreach_queue', postgresql_where="follow_up_at IS NOT NULL AND status IN ('contacted', 'follow_up')")
    op.drop_index('idx_outreach_assigned_status', table_name='outreach_queue')
    op.drop_table('outreach_queue')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_table('users')
