"""add discovery_candidates table

Revision ID: 4a88908c8aca
Revises: 6c40084298be
Create Date: 2026-04-14 13:38:24.059232

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4a88908c8aca'
down_revision: str | None = '6c40084298be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('google_types', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='[]', nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('raw_result_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default='{}', nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("processing_status IN ('pending', 'processed', 'failed', 'skipped_duplicate')", name='ck_discovery_candidates_status'),
    sa.ForeignKeyConstraint(['query_id'], ['query_bank.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'external_id', name='uq_discovery_candidates_source_external')
    )
    op.create_index('idx_discovery_candidates_query', 'discovery_candidates', ['query_id'], unique=False)
    op.create_index('idx_discovery_candidates_status', 'discovery_candidates', ['processing_status', 'discovered_at'], unique=False)
    op.drop_index(op.f('idx_query_bank_quality'), table_name='query_bank')
    op.create_index('idx_query_bank_quality', 'query_bank', ['quality_score'], unique=False, postgresql_ops={'quality_score': 'DESC NULLS LAST'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_query_bank_quality', table_name='query_bank', postgresql_ops={'quality_score': 'DESC NULLS LAST'})
    op.create_index(op.f('idx_query_bank_quality'), 'query_bank', [sa.literal_column('quality_score DESC NULLS LAST')], unique=False)
    op.drop_index('idx_discovery_candidates_status', table_name='discovery_candidates')
    op.drop_index('idx_discovery_candidates_query', table_name='discovery_candidates')
    op.drop_table('discovery_candidates')
    # ### end Alembic commands ###
